from Game import Game
from Deck import Deck
from Card import Card

if __name__ == '__main__':
    card1 = Card(1, "rosu", "inima", "", 0, 0, 0, 0)
    card2 = Card(2, "rosu", "inima", "", 0, 0, 0, 0)
    card3 = Card(3, "rosu", "inima", "", 0, 0, 0, 0)
    card4 = Card(4, "rosu", "inima", "", 0, 0, 0, 0)
    card5 = Card(5, "rosu", "inima", "", 0, 0, 0, 0)
    card6 = Card(6, "rosu", "inima", "", 0, 0, 0, 0)
    card7 = Card(7, "rosu", "inima", "", 0, 0, 0, 0)
    card8 = Card(8, "rosu", "inima", "", 0, 0, 0, 0)
    card9 = Card(9, "rosu", "inima", "", 0, 0, 0, 0)
    card10 = Card(10, "rosu", "inima", "", 0, 0, 0, 0)
    card11 = Card(11, "rosu", "inima", "", 0, 0, 0, 0)
    card12 = Card(12, "rosu", "inima", "", 0, 0, 0, 0)
    card13 = Card(13, "rosu", "inima", "", 0, 0, 0, 0)
    card14 = Card(1, "rosu", "romb", "", 0, 0, 0, 0)
    card15 = Card(2, "rosu", "romb", "", 0, 0, 0, 0)
    card16 = Card(3, "rosu", "romb", "", 0, 0, 0, 0)
    card17 = Card(4, "rosu", "romb", "", 0, 0, 0, 0)
    card18 = Card(5, "rosu", "romb", "", 0, 0, 0, 0)
    card19 = Card(6, "rosu", "romb", "", 0, 0, 0, 0)
    card20 = Card(7, "rosu", "romb", "", 0, 0, 0, 0)
    card21 = Card(8, "rosu", "romb", "", 0, 0, 0, 0)
    card22 = Card(9, "rosu", "romb", "", 0, 0, 0, 0)
    card23 = Card(10, "rosu", "romb", "", 0, 0, 0, 0)
    card24 = Card(11, "rosu", "romb", "", 0, 0, 0, 0)
    card25 = Card(12, "rosu", "romb", "", 0, 0, 0, 0)
    card26 = Card(13, "rosu", "romb", "", 0, 0, 0, 0)
    card27 = Card(1, "negru", "frunza", "", 0, 0, 0, 0)
    card28 = Card(2, "negru", "frunza", "", 0, 0, 0, 0)
    card29 = Card(3, "negru", "frunza", "", 0, 0, 0, 0)
    card30 = Card(4, "negru", "frunza", "", 0, 0, 0, 0)
    card31 = Card(5, "negru", "frunza", "", 0, 0, 0, 0)
    card32 = Card(6, "negru", "frunza", "", 0, 0, 0, 0)
    card33 = Card(7, "negru", "frunza", "", 0, 0, 0, 0)
    card34 = Card(8, "negru", "frunza", "", 0, 0, 0, 0)
    card35 = Card(9, "negru", "frunza", "", 0, 0, 0, 0)
    card36 = Card(10, "negru", "frunza", "", 0, 0, 0, 0)
    card37 = Card(11, "negru", "frunza", "", 0, 0, 0, 0)
    card38 = Card(12, "negru", "frunza", "", 0, 0, 0, 0)
    card39 = Card(13, "negru", "frunza", "", 0, 0, 0, 0)
    card40 = Card(1, "negru", "trefla", "", 0, 0, 0, 0)
    card41 = Card(2, "negru", "trefla", "", 0, 0, 0, 0)
    card42 = Card(3, "negru", "trefla", "", 0, 0, 0, 0)
    card43 = Card(4, "negru", "trefla", "", 0, 0, 0, 0)
    card44 = Card(5, "negru", "trefla", "", 0, 0, 0, 0)
    card45 = Card(6, "negru", "trefla", "", 0, 0, 0, 0)
    card46 = Card(7, "negru", "trefla", "", 0, 0, 0, 0)
    card47 = Card(8, "negru", "trefla", "", 0, 0, 0, 0)
    card48 = Card(9, "negru", "trefla", "", 0, 0, 0, 0)
    card49 = Card(10, "negru", "trefla", "", 0, 0, 0, 0)
    card50 = Card(11, "negru", "trefla", "", 0, 0, 0, 0)
    card51 = Card(12, "negru", "trefla", "", 0, 0, 0, 0)
    card52 = Card(13, "negru", "trefla", "", 0, 0, 0, 0)

    deck = Deck()
    deck.add_card_to_deck(card1)
    deck.add_card_to_deck(card2)
    deck.add_card_to_deck(card3)
    deck.add_card_to_deck(card4)
    deck.add_card_to_deck(card5)
    deck.add_card_to_deck(card6)
    deck.add_card_to_deck(card7)
    deck.add_card_to_deck(card8)
    deck.add_card_to_deck(card9)
    deck.add_card_to_deck(card10)
    deck.add_card_to_deck(card11)
    deck.add_card_to_deck(card12)
    deck.add_card_to_deck(card13)
    deck.add_card_to_deck(card14)
    deck.add_card_to_deck(card15)
    deck.add_card_to_deck(card16)
    deck.add_card_to_deck(card17)
    deck.add_card_to_deck(card18)
    deck.add_card_to_deck(card19)
    deck.add_card_to_deck(card20)
    deck.add_card_to_deck(card21)
    deck.add_card_to_deck(card22)
    deck.add_card_to_deck(card23)
    deck.add_card_to_deck(card24)
    deck.add_card_to_deck(card25)
    deck.add_card_to_deck(card26)
    deck.add_card_to_deck(card27)
    deck.add_card_to_deck(card28)
    deck.add_card_to_deck(card29)
    deck.add_card_to_deck(card30)
    deck.add_card_to_deck(card31)
    deck.add_card_to_deck(card32)
    deck.add_card_to_deck(card33)
    deck.add_card_to_deck(card34)
    deck.add_card_to_deck(card35)
    deck.add_card_to_deck(card36)
    deck.add_card_to_deck(card37)
    deck.add_card_to_deck(card38)
    deck.add_card_to_deck(card39)
    deck.add_card_to_deck(card40)
    deck.add_card_to_deck(card41)
    deck.add_card_to_deck(card42)
    deck.add_card_to_deck(card43)
    deck.add_card_to_deck(card44)
    deck.add_card_to_deck(card45)
    deck.add_card_to_deck(card46)
    deck.add_card_to_deck(card47)
    deck.add_card_to_deck(card48)
    deck.add_card_to_deck(card49)
    deck.add_card_to_deck(card50)
    deck.add_card_to_deck(card51)
    deck.add_card_to_deck(card52)

    game = Game(deck)
    game.arange()
    game.show_Table()
